import type {
  AuthStatus, AppSettings, CarryoverDecision, Category, Credentials, Envelope, FrequentCategory, Invite, NewInvite, Registration, EnvelopePeriod, SaveEnvelope, SaveEnvelopeTarget, SaveCategory, Recurring, SafeToSpend, SaveIncome, SaveRecurring, SaveTaxProfile, SaveTransaction,
  Allocation, SaveAllocation, IncomePreview, OpeningBalance, SaveOpeningBalance, SaveSavingsEntry, SaveSavingsPlan, Savings, SaveTransfer, Stats, TaxDefaults, TaxProfile, Transaction,
  ImportPreview, ImportResult, ImportRowToSave,
  Debts, SaveDebt, SaveDebtPayment, MonthlyNeed, CategoryKind, RecentSpending, SpendWindow,
  TaxActuals as TaxActualsType, SaveTaxActuals,
} from './types'
import {
  apiBase, deviceName, forgetDeviceToken, isNative, readDeviceToken, readDeviceTokenId, saveDeviceToken,
} from './native'

/// The secret exists in this shape exactly once — on the way from the server into storage.
interface IssuedDeviceToken { id: number; name: string; token: string }

/// A device in the owner's list. No secret here: it cannot be read back, by anyone.
export interface Device {
  id: number
  name: string
  createdAt: string
  lastUsedAt: string | null
}

/// Called whenever the server says "not you" — a cookie can expire mid-session, and the
/// screen must fall back to the login form instead of showing a broken dashboard.
let onUnauthorized: () => void = () => {}
export function setOnUnauthorized(handler: () => void) {
  onUnauthorized = handler
}

async function http<T>(url: string, options?: RequestInit): Promise<T> {
  // In the browser this is a no-op on both counts: the base is empty and there is no token,
  // so the request goes out exactly as it always did, carrying the cookie.
  const token = await readDeviceToken()
  // FormData must set its own Content-Type: the boundary is generated by the browser, and a
  // hand-written 'application/json' here makes the server unable to find the file at all.
  const isForm = options?.body instanceof FormData
  const res = await fetch(apiBase() + url, {
    ...options,
    headers: {
      ...(isForm ? {} : { 'Content-Type': 'application/json' }),
      ...(token ? { Authorization: `Bearer ${token}` } : {}),
      ...options?.headers,
    },
  })
  if (res.status === 401 && !url.startsWith('/api/auth')) onUnauthorized()
  if (!res.ok) {
    let message = `HTTP ${res.status}`
    try {
      // ProblemDetails (RFC 7807), which is what the API returns: the sentence written for
      // the user lives in `detail`. This used to look for `error`, a field the API has never
      // sent — so every failure reached the screen as "HTTP 400" and the actual reason
      // («У банці лише 240.00») was thrown away on the way.
      const body = await res.json()
      const detail = body?.detail ?? body?.title ?? body?.error
      if (typeof detail === 'string' && detail !== '') message = detail
    } catch {
      /* body is not JSON — keep the status message */
    }
    // Logged as well as thrown: a component may swallow the error into a red line the user
    // then screenshots, and the console is where the method, url and status still are.
    console.error(`API ${options?.method ?? 'GET'} ${url} → ${res.status}: ${message}`)
    throw new Error(message)
  }
  if (res.status === 204) return undefined as T
  return res.json() as Promise<T>
}

export const api = {
  getAuthStatus: () => http<AuthStatus>('/api/auth/me'),
  /// Same screen, two different doors behind it. The browser gets a session cookie; the
  /// native shell trades the password for a device token once and never asks again — which
  /// is also the credential the home-screen widget will read.
  login: async (c: Credentials) => {
    if (!isNative()) {
      await http<void>('/api/auth/login', { method: 'POST', body: JSON.stringify(c) })
      return
    }

    const issued = await http<IssuedDeviceToken>('/api/auth/device-tokens', {
      method: 'POST',
      body: JSON.stringify({ ...c, name: deviceName() }),
    })
    await saveDeviceToken(issued.id, issued.token)
  },

  logout: async () => {
    if (!isNative()) {
      await http<void>('/api/auth/logout', { method: 'POST' })
      return
    }

    // Cut the token off on the server as well, so signing out of a phone that is then lost
    // means something. Local state is cleared either way: being unable to reach the server
    // must not leave the app signed in.
    const id = await readDeviceTokenId()
    try {
      if (id) await http<void>(`/api/auth/device-tokens/${id}`, { method: 'DELETE' })
    } finally {
      await forgetDeviceToken()
    }
  },

  getDevices: () => http<Device[]>('/api/auth/device-tokens'),
  revokeDevice: (id: number) =>
    http<void>(`/api/auth/device-tokens/${id}`, { method: 'DELETE' }),
  changePassword: (currentPassword: string, newPassword: string) =>
    http<void>('/api/auth/password', {
      method: 'POST', body: JSON.stringify({ currentPassword, newPassword }),
    }),
  changeEmail: (password: string, email: string) =>
    http<void>('/api/auth/email', { method: 'POST', body: JSON.stringify({ password, email }) }),
  signOutEverywhere: () => http<void>('/api/auth/sign-out-everywhere', { method: 'POST' }),

  /// The file goes as multipart, so no 'Content-Type': the browser must set it along with the
  /// boundary — a hand-written header breaks form parsing on the server.
  previewImport: async (file: File) => {
    const body = new FormData()
    body.append('file', file)
    return http<ImportPreview>('/api/import/preview', { method: 'POST', body })
  },
  commitImport: (rows: ImportRowToSave[]) =>
    http<ImportResult>('/api/import/commit', { method: 'POST', body: JSON.stringify({ rows }) }),

  register: (r: Registration) =>
    http<void>('/api/auth/register', { method: 'POST', body: JSON.stringify(r) }),

  getInvites: () => http<Invite[]>('/api/auth/invites'),

  /// The response carries the only readable copy of the code — it is hashed on the server.
  createInvite: (note: string) =>
    http<NewInvite>('/api/auth/invites', { method: 'POST', body: JSON.stringify({ note }) }),

  revokeInvite: (id: number) =>
    http<void>(`/api/auth/invites/${id}`, { method: 'DELETE' }),

  /// One side of the ledger, or both when nothing is asked for — the settings screen lists
  /// everything, the entry forms ask for the side they are about.
  getCategories: (kind?: CategoryKind) =>
    http<Category[]>(`/api/categories${kind ? `?kind=${kind}` : ''}`),

  /// The home screen's one-tap shortcuts. Ranked and windowed server-side — see
  /// CategoryService.GetFrequentAsync for why it is not derived from the recent list.
  getFrequentCategories: () => http<FrequentCategory[]>('/api/categories/frequent'),
  createCategory: (c: SaveCategory) =>
    http<Category>('/api/categories', { method: 'POST', body: JSON.stringify(c) }),
  updateCategory: (id: number, c: SaveCategory) =>
    http<Category>(`/api/categories/${id}`, { method: 'PUT', body: JSON.stringify(c) }),
  deleteCategory: (id: number) =>
    http<void>(`/api/categories/${id}`, { method: 'DELETE' }),

  getTransactions: (take = 20) => http<Transaction[]>(`/api/transactions?take=${take}`),
  createTransaction: (tx: SaveTransaction) =>
    http<Transaction>('/api/transactions', { method: 'POST', body: JSON.stringify(tx) }),
  createIncome: (i: SaveIncome) =>
    http<Transaction>('/api/transactions/income', { method: 'POST', body: JSON.stringify(i) }),
  /// Correcting an invoice is its own route, because income still carries VAT.
  updateIncome: (id: number, i: SaveIncome) =>
    http<Transaction>(`/api/transactions/${id}/income`, { method: 'PUT', body: JSON.stringify(i) }),
  updateTransaction: (id: number, tx: SaveTransaction) =>
    http<Transaction>(`/api/transactions/${id}`, { method: 'PUT', body: JSON.stringify(tx) }),
  deleteTransaction: (id: number) =>
    http<void>(`/api/transactions/${id}`, { method: 'DELETE' }),

  getOpeningBalance: () => http<OpeningBalance>('/api/opening-balance'),
  setOpeningBalance: (b: SaveOpeningBalance) =>
    http<OpeningBalance>('/api/opening-balance', { method: 'PUT', body: JSON.stringify(b) }),
  clearOpeningBalance: () => http<OpeningBalance>('/api/opening-balance', { method: 'DELETE' }),

  getSafeToSpend: () => http<SafeToSpend>('/api/summary/safe-to-spend'),

  decideCarryover: (decision: CarryoverDecision) =>
    http<void>('/api/carryover', { method: 'POST', body: JSON.stringify({ decision }) }),

  getStats: (months: number, month: string | null) =>
    http<Stats>(`/api/stats?months=${months}${month ? `&month=${month}` : ''}`),

  getSettings: () => http<AppSettings>('/api/settings'),
  setDisplayCurrency: (currency: string) =>
    http<AppSettings>('/api/settings/currency', { method: 'PUT', body: JSON.stringify({ currency }) }),
  setPeriodStartDay: (day: number) =>
    http<AppSettings>('/api/settings/period-start-day', { method: 'PUT', body: JSON.stringify({ day }) }),

  getEnvelopeHistory: (id: number, periods = 6) =>
    http<EnvelopePeriod[]>(`/api/envelopes/${id}/history?periods=${periods}`),
  createEnvelope: (e: SaveEnvelope) =>
    http<Envelope>('/api/envelopes', { method: 'POST', body: JSON.stringify(e) }),
  updateEnvelope: (id: number, e: SaveEnvelope) =>
    http<Envelope>(`/api/envelopes/${id}`, { method: 'PUT', body: JSON.stringify(e) }),
  /// A target on a jar: an amount (in the currency being displayed) and, optionally, a date.
  /// `amount: null` takes the target off.
  setEnvelopeTarget: (id: number, t: SaveEnvelopeTarget) =>
    http<Envelope>(`/api/envelopes/${id}/target`, { method: 'PUT', body: JSON.stringify(t) }),
  /// Takes a jar out of sight, not out of history: its movements stay, so this only works on an
  /// empty jar — the server answers with the balance if there is anything left in it.
  deleteEnvelope: (id: number) =>
    http<void>(`/api/envelopes/${id}`, { method: 'DELETE' }),

  getMonthlyNeed: () => http<MonthlyNeed>('/api/summary/monthly-need'),

  getRecurring: () => http<Recurring[]>('/api/recurring'),
  createRecurring: (r: SaveRecurring) =>
    http<Recurring>('/api/recurring', { method: 'POST', body: JSON.stringify(r) }),
  updateRecurring: (id: number, r: SaveRecurring) =>
    http<Recurring>(`/api/recurring/${id}`, { method: 'PUT', body: JSON.stringify(r) }),
  deleteRecurring: (id: number) =>
    http<void>(`/api/recurring/${id}`, { method: 'DELETE' }),
  /// The id is one CHARGE's, not the subscription's: the same subscription can have another
  /// occurrence still waiting behind this one.
  confirmCharge: (transactionId: number) =>
    http<void>(`/api/recurring/charges/${transactionId}/confirm`, { method: 'POST' }),
  /// Takes «Оплачено ✓» back. The tick is one tap on a card that appears unbidden, so it gets
  /// mis-tapped — and deleting the charge says something else entirely: that it never happened.
  unconfirmCharge: (transactionId: number) =>
    http<void>(`/api/recurring/charges/${transactionId}/unconfirm`, { method: 'POST' }),

  getRecentSpending: (window: SpendWindow) =>
    http<RecentSpending>(`/api/stats/recent?window=${window}`),

  /// Downloads an export and hands it to the browser as a file.
  ///
  /// Fetched rather than linked to: the native build authenticates with a Bearer token the
  /// `http` helper adds, and a plain <a href> would arrive without it and be refused. The
  /// filename comes from the server's Content-Disposition, so the date in it is the server's.
  downloadExport: async (what: 'ledger.csv' | 'backup.json') => {
    const token = await readDeviceToken()
    const res = await fetch(`${apiBase()}/api/export/${what}`, {
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    })
    if (res.status === 401) onUnauthorized()
    if (!res.ok) throw new Error(`Не вийшло вивантажити (HTTP ${res.status})`)

    const disposition = res.headers.get('Content-Disposition') ?? ''
    const named = /filename="?([^";]+)"?/.exec(disposition)?.[1]
    const url = URL.createObjectURL(await res.blob())
    try {
      const a = document.createElement('a')
      a.href = url
      a.download = named ?? `finance-${what}`
      a.click()
    } finally {
      // Revoked on the next tick: doing it synchronously can cancel the download in Safari.
      setTimeout(() => URL.revokeObjectURL(url), 1000)
    }
  },

  getTaxProfile: () => http<TaxProfile>('/api/tax/profile'),
  saveTaxProfile: (p: SaveTaxProfile) =>
    http<TaxProfile>('/api/tax/profile', { method: 'PUT', body: JSON.stringify(p) }),
  getTaxDefaults: () => http<TaxDefaults>('/api/tax/defaults'),
  /// What the bookkeeper said for a month. No month = the one being lived in.
  getTaxActuals: (month?: string) =>
    http<TaxActualsType>(`/api/tax/actuals${month ? `?month=${month}` : ''}`),
  saveTaxActuals: (a: SaveTaxActuals) =>
    http<TaxActualsType>('/api/tax/actuals', { method: 'PUT', body: JSON.stringify(a) }),
  getSavings: () => http<Savings>('/api/savings'),
  saveSavingsPlan: (p: SaveSavingsPlan) =>
    http<Savings>('/api/savings/plan', { method: 'PUT', body: JSON.stringify(p) }),
  transferBetweenEnvelopes: (t: SaveTransfer) =>
    http<Savings>('/api/savings/transfer', { method: 'POST', body: JSON.stringify(t) }),
  addSavingsEntry: (e: SaveSavingsEntry) =>
    http<Savings>('/api/savings/entries', { method: 'POST', body: JSON.stringify(e) }),
  deleteSavingsEntry: (id: number) =>
    http<Savings>(`/api/savings/entries/${id}`, { method: 'DELETE' }),
  updateSavingsEntry: (id: number, e: SaveSavingsEntry) =>
    http<Savings>(`/api/savings/entries/${id}`, { method: 'PUT', body: JSON.stringify(e) }),

  /// Every debt write answers with the whole picture, like savings does: the totals, the
  /// reserve and each debt's remainder all move together, and a partial answer would let the
  /// screen show a paid-off debt beside a total that still counts it.
  getDebts: () => http<Debts>('/api/debts'),
  createDebt: (d: SaveDebt) =>
    http<Debts>('/api/debts', { method: 'POST', body: JSON.stringify(d) }),
  updateDebt: (id: number, d: SaveDebt) =>
    http<Debts>(`/api/debts/${id}`, { method: 'PUT', body: JSON.stringify(d) }),
  deleteDebt: (id: number) => http<Debts>(`/api/debts/${id}`, { method: 'DELETE' }),
  setDebtClosed: (id: number, closed: boolean) =>
    http<Debts>(`/api/debts/${id}/closed`, { method: 'POST', body: JSON.stringify({ closed }) }),
  addDebtPayment: (id: number, p: SaveDebtPayment) =>
    http<Debts>(`/api/debts/${id}/payments`, { method: 'POST', body: JSON.stringify(p) }),
  deleteDebtPayment: (paymentId: number) =>
    http<Debts>(`/api/debts/payments/${paymentId}`, { method: 'DELETE' }),

  getAllocations: () => http<Allocation>('/api/allocations'),
  saveAllocation: (a: SaveAllocation) =>
    http<Allocation>('/api/allocations', { method: 'PUT', body: JSON.stringify(a) }),

  resetDevData: () => http<{ message: string }>('/api/dev/reset', { method: 'POST' }),
  seedDevData: () => http<{ message: string }>('/api/dev/seed', { method: 'POST' }),

  previewIncome: (amount: number, amountIncludesVat: boolean) =>
    http<IncomePreview>('/api/tax/income-preview', {
      method: 'POST',
      body: JSON.stringify({ amount, amountIncludesVat }),
    }),
}
